name: sar2-d2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  - mypy
  - pytest
  - pip
  - pyyaml
  - types-pyyaml
  - types-requests
  - pip:
    - maap-py

# # Used by conda lock
# category: dev
# platforms:
#   - linux-64
#   - osx-64
#   - osx-arm64
