name: sar2-d2
channels:
  - conda-forge
  - nodefaults  # force everything to come from conda-forge channel
dependencies:
  - isce3=0.24.1  # R4.0.4 delivery
  - python >=3.12
  - pip:
      - git+https://github.com/MAAP-Project/maap-py.git
  - sardem  # to download and crop the SRTM DEM

# # Used by conda lock
# platforms:
#   - linux-64
#   - osx-64
#   - osx-arm64
